export function createOfflineNetClient(roomId = 'offline') {
  return {
    ws: null,
    roomId,
    localId: 'offline-local',
    connected: false,
    remotePlayers: new Map(),
    remotePredators: new Map(),
    pushBalls: [],
    mounts: [],
    ropes: [],
    fans: [],
    physicalTasks: [],
    completedTaskIds: [],
    completedTaskRevision: 0,
    cheesePickups: [],
    round: null,
    extractionPortals: [],
    adversary: { playerId: null, available: false, safeRadius: 0 },
    serverState: null,
    serverSeq: -1,
    ping: 0,
    heroClaims: {},
    unlockItems: [],
    dronePurchase: { ok: false, pending: false, message: '' },
    _listeners: new Set(),
    connect() {},
    disconnect() {},
    on(fn) {
      this._listeners.add(fn);
      return () => this._listeners.delete(fn);
    },
    sendInput() { return 0; },
    sendSpawnExtraBall() {},
    sendTaskComplete() {},
    sendSqueak() {},
    sendUnlockPickup() {},
    sendClaimHero() {},
    sendDronePurchase() {},
    sendDisplayName() {},
    async fetchLeaderboard() { return null; },
  };
}
